apiVersion: v1
kind: Service
metadata:
  name: ping-poller-svc
  namespace: default
spec:
  selector:
    app: ping-poller
  type: LoadBalancer
  ports:
  - name: ping-poller
    protocol: TCP
    port: 5000
    targetPort: 5000
